/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/**/*.{js,ts,jsx,tsx}",
    "./index.html",
  ],
  theme: {
    extend: {
      colors: {
        primaryBg: 'var(--primary-bg)',
        icon: 'var(--icon)',
        iconDark: 'var(--icon-dark)',
        text: 'var(--text)',
        textDark: 'var(--text-dark)',
        textLight: 'var(--text-light)',
        textStreak: 'var(--text-streak)',
        button: 'var(--button)',
        buttonConfirm: 'var(--button-confirm)',
        container: 'var(--container)',
        day: 'var(--day)',
        dayActive: 'var(--day-active)',
        border: 'var(--border)',
        connection: 'var(--connection)',
        timer: 'var(--timer)',
        // primaryBg: 'var(--primary-bg)',
        // secondaryBg: 'var(--secondary-bg)',
        // tertiaryBg: 'var(--tertiary-bg)',
        // textDark: 'var(--text-dark)',
        // textAccent: 'var(--text-accent)',
        // textAccentLight: 'var(--text-accent-light)',
        // textLight: 'var(--text-light)',
        // buttonDark: 'var(--button-dark-bg)',
        // tileBg: 'var(--tile-bg)',
        // secondaryTileBg: 'var(--secondary-tile-bg)',
        // darkTileBg: 'var(--dark-tile-bg)',
        // logoLight: 'var(--logo-light)',
        // logoDark: 'var(--logo-dark)',
      },
    },
  },
  plugins: [],
}